server:
  port: 5004
  application:
    name: greeting-service
greeting-service:
  greeting: "Hello"
  default-value: "World - Dev Default"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
