server:
  port: 5004
  application:
    name: greeting-service
greeting-service:
  greeting: "Cia"
  default-value: "Mondo - Prod"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
