server:
  port: 5004
  application:
    name: greeting-service
greeting-service:
  greeting: "Olá"
  default-value: "Mundo - QA"
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
